### ISSUE TITLE
Text rendering is altered

### ISSUE THREAD

**Issue by ghivert** [file-icons/atom#708]
Hi!

I'm a huge fan of the package, but I noticed some bugs with the last version of atom: the name of a file is not always good.

For instance:

<img width="1114" alt="capture d ecran 2018-02-20 a 12 13 15 pm" src="https://user-images.githubusercontent.com/7314118/36421115-9a596628-1637-11e8-8717-835c59022ad5.png">

Any idea?

**Comment by Alhadis** [comment]
Hi @ghivert,

It's a styling issue. What styles do you have in `~/.atom/styles.less`?

**Comment by ghivert** [comment]
```less
/*
 * Your Stylesheet
 *
 * This stylesheet is loaded when Atom starts up and is reloaded automatically
 * when it is changed and saved.
 *
 * Add your own CSS or Less to fully customize Atom.
 * If you are unfamiliar with Less, you can read more about it here:
 * http://lesscss.org
 */


/*
 * Examples
 * (To see them, uncomment and save)
 */

// style the background color of the tree view
.tree-view {
  // background-color: whitesmoke;
}

// style the background and foreground colors on the atom-text-editor-element itself
atom-text-editor {
  // color: white;
  // background-color: hsl(180, 24%, 12%);
  text-rendering: optimizeLegibility;
}

// To style other content in the text editor's shadow DOM, use the ::shadow expression
atom-text-editor.cursor {
  // border-color: red;
}

atom-text-editor .vertical-scrollbar,
atom-text-editor.editor .vertical-scrollbar {
  opacity: 0;
  width: 0;
}

.syntax--comment {
  font-style: normal;
}

atom-text-editor .syntax--comment {
  font-style: normal;
}

[data-font='hasklig-medium'] atom-text-editor .syntax--comment {
  font-style: normal;
}

atom-text-editor .syntax--underline {
  text-decoration: none;
}

.lisp-paredit-status {
  display: none;
}

atom-text-editor, html {
  atom-text-editor-minimap {
    .minimap-visible-area {
      background-color: #7c7c7c;
      // Color of Visible area.
      opacity: 0;
      // Default 0 when you not working with minimap
      cursor: default;
      // Change cursor style to pointer.
      transition: 0.5s opacity;
      // Better UI.
      &:hover {
        opacity: 0.2;
      } // Only display Minimap visible area when working.
      &:active {
        cursor: default;
      } // Change cursor when dragging.
    }
    &:hover {
      .minimap-visible-area {
        opacity: 0.2;
        transition: opacity 1s;
      } // When Hover to all minimap area, visible area will display.
    }

    &:active {
      .minimap-visible-area {
        opacity: 0.2;
        transition: opacity 0.5s;
      } // Display Minimap visible area when dragging.
    }
  }
}

atom-text-editor {
  .syntax--source.syntax--js.syntax--jsx {
    .syntax--graphql {
      .syntax--alias {
        font-style: normal
      }
      .syntax--support.syntax--type.syntax--builtin {
        -webkit-filter: brightness(80%);
      }
    }
    .syntax--jsx {
      .syntax--entity {
        &.syntax--other {
          &.syntax--attribute-name {
             font-style: normal // color: @cyan;
          }
        }
      }
      .syntax--constant.syntax--character.syntax--entity {
        font-style: normal
      }
    }
  }
  .syntax--source.syntax--css.syntax--styled {
    .syntax--support.syntax--type.syntax--property-name.syntax--unknown {
      -webkit-filter: brightness(75%);
    }
  }
}

.linter-elm-make-inferred-type-annotation {
  font-style: normal;
}
```

**Comment by Alhadis** [comment]
Have you installed `file-icons` to `~/.atom/packages/file-icons`?

If so, check what styles are being applied to the affected tabs. Open the inspector tools, select the tab's label and screenshot/copy the properties that're being applied (visible in the bottom-left panel below):

<img width="400" src="https://user-images.githubusercontent.com/2346707/36423348-c0f67cb0-1693-11e8-8972-1f10a35eb9c4.png" />

**Comment by kencruz07** [comment]
Hi @Alhadis and @ghivert 

I'm also having this same issue with atom
Atom 1.24.0
File Icons 2.1.17

It seems that this happens with the `ruby-icon` class. Upon using the inspector, the `ruby-icon` class is using "Octicons Regular".

![image](https://user-images.githubusercontent.com/6532866/36830619-5cf2ddf8-1d5f-11e8-9634-270982e73d85.png)

As a quick fix, I've modified `styles.less` with:
```css
.ruby-icon {
  font-family: inherit;
  font-size: inherit;
}
```
