### ISSUE TITLE
Wrong classname when I use matchName Api to get the icon classname of  txt file

### ISSUE THREAD

**Issue by Jocs** [file-icons/atom#865]
I have a txt file, for example `mock.txt` through [matchName](https://github.com/file-icons/atom/blob/6854acdd01ecf6019eaf4e8e2040410ce7ae5a7c/lib/icons/icon-tables.js#L67) api to get the icon's classname, which is `icon-file-text`, but I did not find the corresponding classname(`icon-file-text`) in `styles/icons.less` file.

Did I go wrong?

https://github.com/file-icons/atom/blob/5e56b79380e7d8563b9f90da461a7947b802f03e/lib/icons/.icondb.js#L1192

**Comment by Alhadis** [comment]
A handful of icons are provided by Atom's [core styling](https://github.com/atom/atom/blob/7033a5a22f260a54c0ffb69f45d12622478778df/static/variables/octicon-utf-codes.less#L88-L98). The ones used by File-Icons are:

* [`icon-circuit-board`](https://github.com/atom/atom/blob/7033a5a22f260a54c0ffb69f45d12622478778df/static/variables/octicon-utf-codes.less#L56)
* [`icon-file-pdf`](https://github.com/atom/atom/blob/7033a5a22f260a54c0ffb69f45d12622478778df/static/variables/octicon-utf-codes.less#L93)
* [`icon-file-text`](https://github.com/atom/atom/blob/7033a5a22f260a54c0ffb69f45d12622478778df/static/variables/octicon-utf-codes.less#L97)
* [`icon-mail`](https://github.com/atom/atom/blob/7033a5a22f260a54c0ffb69f45d12622478778df/static/variables/octicon-utf-codes.less#L151)
* [`icon-paintcan`](https://github.com/atom/atom/blob/7033a5a22f260a54c0ffb69f45d12622478778df/static/variables/octicon-utf-codes.less#L173)
* [`icon-star`](https://github.com/atom/atom/blob/7033a5a22f260a54c0ffb69f45d12622478778df/static/variables/octicon-utf-codes.less#L220)

Here's the equivalent CSS, if you need it outside of Atom:

```css
.icon-circuit-board::before { content: "\f0d6"; font: 16px/1 "Octicons Regular"; }
.icon-file-pdf::before      { content: "\f014"; font: 16px/1 "Octicons Regular"; }
.icon-file-text::before     { content: "\f011"; font: 16px/1 "Octicons Regular"; }
.icon-mail::before          { content: "\f03b"; font: 16px/1 "Octicons Regular"; }
.icon-paintcan::before      { content: "\f0d1"; font: 16px/1 "Octicons Regular"; }
.icon-star::before          { content: "\f02a"; font: 16px/1 "Octicons Regular"; }
```

This inconsistency is annoying, but it's for backwards (and forwards) compatibility. Basically, any class-name prefixed by `icon-` is guaranteed *not* to be defined by File-Icons, which uses the `-icon` **suffix** instead.
